version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args: 
        GITHUB_USER: 'example'
        GITHUB_TOKEN: 'example'
        GITHUB_REPOSITORY: 'example/example.git'
        HUGO_VERSION: '0.81.0'
    environment:
      SITE_URL: 'example.net'
    ports: 
      - '80:80'
    restart: unless-stopped